"""initial

Revision ID: 542bae4a8155
Revises: 
Create Date: 2026-02-25 16:30:59.038665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542bae4a8155'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('career_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('career_path', sa.String(length=100), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.String(length=500), nullable=True),
    sa.Column('prefer_government_job', sa.Boolean(), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('income_expectation', sa.Integer(), nullable=True),
    sa.Column('work_life_balance', sa.String(length=20), nullable=True),
    sa.Column('study_abroad', sa.Boolean(), nullable=True),
    sa.Column('entrepreneurship', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_preferences_id'), 'career_preferences', ['id'], unique=False)
    op.create_table('career_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('final_report', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_reports_id'), 'career_reports', ['id'], unique=False)
    op.create_index(op.f('ix_career_reports_student_id'), 'career_reports', ['student_id'], unique=False)
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interests_id'), 'interests', ['id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('student_academic_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('stream', sa.String(length=100), nullable=False),
    sa.Column('current_class', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('strongest_subject', sa.String(length=100), nullable=False),
    sa.Column('weakest_subject', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_academic_profiles_id'), 'student_academic_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_student_academic_profiles_student_id'), 'student_academic_profiles', ['student_id'], unique=False)
    op.create_table('student_subject_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_profile_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_profile_id'], ['student_academic_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_subject_marks_academic_profile_id'), 'student_subject_marks', ['academic_profile_id'], unique=False)
    op.create_index(op.f('ix_student_subject_marks_id'), 'student_subject_marks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_subject_marks_id'), table_name='student_subject_marks')
    op.drop_index(op.f('ix_student_subject_marks_academic_profile_id'), table_name='student_subject_marks')
    op.drop_table('student_subject_marks')
    op.drop_index(op.f('ix_student_academic_profiles_student_id'), table_name='student_academic_profiles')
    op.drop_index(op.f('ix_student_academic_profiles_id'), table_name='student_academic_profiles')
    op.drop_table('student_academic_profiles')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_interests_id'), table_name='interests')
    op.drop_table('interests')
    op.drop_index(op.f('ix_career_reports_student_id'), table_name='career_reports')
    op.drop_index(op.f('ix_career_reports_id'), table_name='career_reports')
    op.drop_table('career_reports')
    op.drop_index(op.f('ix_career_preferences_id'), table_name='career_preferences')
    op.drop_table('career_preferences')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
